version: '3.8'

services:
  frontend:
    container_name: mst-template
    image: mst-template
    build:
      target: development
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
